# Generated by Django 3.0.8 on 2020-07-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friday',
            field=models.CharField(default='physisics', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='monday',
            field=models.CharField(default='physisics', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='saturday',
            field=models.CharField(default='physisics', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='sunday',
            field=models.CharField(default='physisics', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='thursday',
            field=models.CharField(default='physisics', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='tuesday',
            field=models.CharField(default='physisics', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='wednesday',
            field=models.CharField(default='physisics', max_length=30),
        ),
    ]
