# Generated by Django 3.0.8 on 2020-07-30 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20200727_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sunday',
        ),
    ]
